In [8]:
import numpy as np
list=np.array([["Ram","ravi"],["suraj","amkur"]])
print(list[0])
print(list[1])

['Ram' 'ravi']
['suraj' 'amkur']


In [9]:
arr=np.array([10,20,30,40,50])
print(arr[[1,3]])

[20 40]


In [10]:
lst=np.array([2,3,5,7,8])
print(lst[lst>5])

[7 8]


In [11]:
marks=np.array([25,79,89,99,67,51])
print(marks[marks>45])

[79 89 99 67 51]


In [12]:
for i in [11,22,33,44,55]:
    print(i)

11
22
33
44
55


In [13]:
arr=np.array([10,20,30,40])
for i in arr:
    print(i)

10
20
30
40


In [14]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr=np.array([[11,22],[33,44],[55,66]])
for i in arr:
    print(i)

[11 22]
[33 44]
[55 66]


In [16]:
arr=np.array([[11,22],[33,44]])
print(arr)

[[11 22]
 [33 44]]


In [17]:
for i in np.nditer(arr):
    print(i)

11
22
33
44


In [18]:
arr=([10,20,30,40])
for i in np.nditer(arr):
    print(i)

(array(10), array(20), array(30), array(40))


In [46]:
arr1=([11,22,33,44])
arr2=([55,66,77,88])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[11 22 33 44 55 66 77 88]
