In [1]:
import pandas as pd
orders=pd.Series(["Delivered","Cancelled","Delivered","Pending"])
print(orders.dtype)

object


In [3]:
orders=pd.Series(["Delivered","Cancelled","Delivered","Pending"])
orders=orders.astype("category")
print(orders.dtype)

category


In [4]:
salary=[1000,2000,3000,4000]
new_salary=[]
for s in salary:
    new_salary.append(s*1.1)
print(new_salary)

[1100.0, 2200.0, 3300.0000000000005, 4400.0]


In [13]:
import numpy as np
salary=np.array([1000,2000,3000,4000,5000])
new_salary=salary*1.1
print(new_salary)

[1100. 2200. 3300. 4400. 5500.]


In [2]:
import numpy as np
price=np.array([10000,20000,30000,40000,50000])
discount=price*0.5
print(discount)


[ 5000. 10000. 15000. 20000. 25000.]


In [3]:
import pandas as pd
data=pd.Series(range(1,10))
sample=data.sample(5)
print(sample)                 #we will get the random output

4    5
6    7
3    4
0    1
2    3
dtype: int64


In [6]:
sample=data.sample(frac=0.5)
print(sample)

0    1
1    2
6    7
3    4
dtype: int64


In [7]:
salary=([50000,60000,70000,80000])
print(np.mean(salary))

65000.0


In [1]:
import numpy as np
salary=([5000,2500,4500,6000,9000,8500])
print(np.median(salary))

5500.0


In [10]:
from scipy import stats
data=[10,20,40,60,30,50,60]
print(stats.mode(data))

ModeResult(mode=np.int64(60), count=np.int64(2))


In [11]:
import numpy as np
salary=([5000,2500,4500,6000,9000,8500])
print(np.max(salary))

9000


In [12]:
salary=([5000,2500,4500,6000,9000,8500])
print(np.min(salary))

2500


In [15]:
salary=([5000,2500,4500,6000,9000,8500])
print(np.max(salary)-np.min(salary))          #to find the range= (max-min)

6500


In [16]:
salary=([100,200,500,600,800,300])
print(np.var(salary))

58055.55555555556


In [17]:
salary=([100,200,500,600,800,300])
print(np.std(salary))

240.94720491334934


In [21]:
mark=([25,85,76,99,100,84])
print(np.mean(mark))
print(np.min(mark))
print(np.max(mark))
print(np.median(mark))
print(np.var(mark))
print(np.std(mark))
print(np.max(mark)-np.min(mark))

78.16666666666667
25
100
84.5
637.1388888888889
25.24161026735198
75


In [22]:
import pandas as pd
data={
      "Name":["mokshuu","rachna","varshu","navya","roshni","apple","prvlika"],
      "Age":[19,20,26,30,45,39,25],
      "City":["knr","jgtl","kpl","vmd","ngl","wrgl","nzb"]
}
details=pd.DataFrame(data)
print(details.sample(3))      

      Name  Age City
4   roshni   45  ngl
2   varshu   26  kpl
6  prvlika   25  nzb


In [26]:
import pandas as pd
student={
    "name":["mokshu","rachhu","navya","vrshuu","mokshuu"],
    "marks":[100,85,74,65,100]
}
details=pd.DataFrame(student)
details.sample(3,random_state=0)    #random sample

,name,marks
2,navya,74
0,mokshu,100
1,rachhu,85


In [25]:
from scipy import stats
mark=([25,85,76,99,100,84])
print(stats.mode(mark))

ModeResult(mode=np.int64(25), count=np.int64(1))


In [27]:
import numpy as np
salary=np.array([1500,6300,9500,7200,8900])
bonus=salary+2500
print(bonus)

[ 4000  8800 12000  9700 11400]
