In [3]:
import numpy as np
arr1=([11,22,33,44])
arr2=([55,66,77,88])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[11 22 33 44 55 66 77 88]


In [4]:
arr=np.array([10,20,30,40,30,50])
x=np.where(arr==30)
print(x)

(array([2, 4]),)


In [5]:
arr=np.array([10,20,30,40,30,50])
x=np.sort(arr)
print(x)

[10 20 30 30 40 50]


In [12]:
import numpy as np
marks=np.array([40,76,83,96,68,56])
print(marks[marks>=45])

[76 83 96 68 56]


In [13]:
marks=np.average([40,76,83,96,68,56])
print(marks)

69.83333333333333


In [16]:
marks1=np.min([40,76,83,96,68,56])
marks2=np.max([40,76,83,96,68,56])
marks3=np.mean([40,76,83,96,68,56])
print(marks1)
print(marks2)
print(marks3)

40
96
69.83333333333333


In [24]:
arr=np.array([10,20,30,40,50])
print(np.power(arr,9))

[      1000000000     512000000000   19683000000000  262144000000000
 1953125000000000]


In [7]:
a=([1,2,3,4,])
b=([5,6,7,8])
c=np.array((a+b))
print(c)

[1 2 3 4 5 6 7 8]


In [8]:
a=(["cup"])
b=(["cake"])
c=np.array((a+b))
print(c)

['cup' 'cake']
