In [1]:
import numpy as np
client1=np.array([100,90,30,67,20])
client2=np.array([67,99,45,67,87])
print(client1+client2)

[167 189  75 134 107]


In [1]:
import numpy as np
arr=np.arange(10)                 #[0,1,2,3,4,5,6,7,8,9]
print(arr[::2])                    #every 2nd element [0,2,4,6,8]
print(arr[1:7:2])                 #from index 1 to 6, step2[1,3,5]

[0 2 4 6 8]
[1 3 5]


In [5]:
import numpy as np
arr=np.arange(10)
print(np.split(arr,2))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [6]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.vstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
