In [1]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
import numpy as np
food=np.array(["biryani,noodles,maggie"])
print(food)
               

['biryani,noodles,maggie']


In [4]:
import numpy as np
arr=np.array([[10,20],[30,40],[50,60]])
print(arr)

[[10 20]
 [30 40]
 [50 60]]


In [5]:
flower=np.array([["daisy,rose"],["lilly,lotus"],["jasmine,gold"]])
print(flower)

[['daisy,rose']
 ['lilly,lotus']
 ['jasmine,gold']]


In [13]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [21]:
abc=np.array([10,20,30,40])
print(np.max(abc))

40


In [20]:
abc=np.array([10,20,30,40])
print(np.min(abc))

10


In [19]:
abc=np.array([10,20,30,40])
print(np.mean(abc))

25.0


In [22]:
a=np.array([10,20,30,40])
print(np.sum(abc))

100


In [24]:
a=np.array([10,20,30,40])
print(np.average(abc))

25.0
