In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [3]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.hstack((a,b)))

[1 2 3 4 5 6 7 8]


In [4]:
arr=np.array([2,3,4,5,6])
print(arr+5)

[ 7  8  9 10 11]


In [5]:
arr=np.array(["a","m","s","k","v"])
print(arr+"n")

['an' 'mn' 'sn' 'kn' 'vn']


In [8]:
arr=np.array([[2,3],[5,6]])
print(arr+[5,7])

[[ 7 10]
 [10 13]]


In [9]:
arr=np.array([[6,8,0],[6,2,3]])
print(arr+[3,4,1])

[[ 9 12  1]
 [ 9  6  4]]
